version: '3'

services:
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
            - ./_docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
        container_name: o2

    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            - db
        container_name: o2_nginx

    db:
        image: mysql:latest
        container_name: o2_db
        restart: always
        environment:
            MYSQL_DATABASE: o2
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8101:3306"

    phpmyadmin:
        container_name: o2_phpmyadmin
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
        ports:
            - "8001:80"
